--миграция данных для поддержки словарем имен регионов с сайта https://3dpro.info/
ALTER TABLE minenergo_schema.region_directory
ADD pro_name TEXT;

update minenergo_schema.region_directory set pro_name = 'Алтайский край (г Барнаул) (01000000000)' where subject_id = 1;
update minenergo_schema.region_directory set pro_name = 'Амурская область (г Благовещенск) (10000000000)' where subject_id = 10;
update minenergo_schema.region_directory set pro_name = 'Архангельская область (г Архангельск) (11000000000)' where subject_id = 11;
update minenergo_schema.region_directory set pro_name = 'Астраханская область (г Астрахань) (12000000000)' where subject_id = 12;
update minenergo_schema.region_directory set pro_name = 'Белгородская область (г Белгород) (14000000000)' where subject_id = 14;
update minenergo_schema.region_directory set pro_name = 'Брянская область (г Брянск) (15000000000)' where subject_id = 15;
update minenergo_schema.region_directory set pro_name = 'Владимирская область (г Владимир) (17000000000)' where subject_id = 17;
update minenergo_schema.region_directory set pro_name = 'Волгоградская область (г Волгоград) (18000000000)' where subject_id = 18;
update minenergo_schema.region_directory set pro_name = 'Вологодская область (г Вологда) (19000000000)' where subject_id = 19;
update minenergo_schema.region_directory set pro_name = 'Воронежская область (г Воронеж) (20000000000)' where subject_id = 20;
update minenergo_schema.region_directory set pro_name = 'Еврейская автономная область (г Биробиджан) (99000000000)' where subject_id = 99;
update minenergo_schema.region_directory set pro_name = 'Забайкальский край (г Чита) (76000000000)' where subject_id = 76;
update minenergo_schema.region_directory set pro_name = 'Республика Саха (Якутия) (г Якутск) (98000000000)' where subject_id = 98;
update minenergo_schema.region_directory set pro_name = 'Ивановская область (г Иваново) (24000000000)' where subject_id = 24;
update minenergo_schema.region_directory set pro_name = 'Иркутская область (г Иркутск) (25000000000)' where subject_id = 25;
update minenergo_schema.region_directory set pro_name = 'Кабардино-Балкарская Республика (г Нальчик) (83000000000)' where subject_id = 83;
update minenergo_schema.region_directory set pro_name = 'Калининградская область (г Калининград) (27000000000)' where subject_id = 27;
update minenergo_schema.region_directory set pro_name = 'Калужская область (г Калуга) (29000000000)' where subject_id = 29;
update minenergo_schema.region_directory set pro_name = 'Карачаево-Черкесская Республика (г Черкесск) (91000000000)' where subject_id = 91;
update minenergo_schema.region_directory set pro_name = 'Кемеровская область (г Кемерово) (32000000000)' where subject_id = 32;
update minenergo_schema.region_directory set pro_name = 'Кировская область (г Киров) (33000000000)' where subject_id = 33;
update minenergo_schema.region_directory set pro_name = 'Костромская область (г Кострома) (34000000000)' where subject_id = 34;
update minenergo_schema.region_directory set pro_name = 'Краснодарский край (г Краснодар) (03000000000)' where subject_id = 3;
update minenergo_schema.region_directory set pro_name = 'Красноярский край (г Красноярск) (04000000000)' where subject_id = 4;
update minenergo_schema.region_directory set pro_name = 'Курганская область (г Курган) (37000000000)' where subject_id = 37;
update minenergo_schema.region_directory set pro_name = 'Курская область (г Курск) (38000000000)' where subject_id = 38;
update minenergo_schema.region_directory set pro_name = 'Ленинградская область (г Санкт-Петербург) (41000000000)' where subject_id = 41;
update minenergo_schema.region_directory set pro_name = 'Липецкая область (г Липецк) (42000000000)' where subject_id = 42;
update minenergo_schema.region_directory set pro_name = 'Республика Марий Эл (г Йошкар-Ола) (88000000000)' where subject_id = 88;
update minenergo_schema.region_directory set pro_name = 'Республика Мордовия (г Саранск) (89000000000)' where subject_id = 89;
update minenergo_schema.region_directory set pro_name = 'Московская область (г Москва) (46000000000)' where subject_id = 46;
update minenergo_schema.region_directory set pro_name = 'Мурманская область (г Мурманск) (47000000000)' where subject_id = 47;
update minenergo_schema.region_directory set pro_name = 'Нижегородская область (г Нижний Новгород) (22000000000)' where subject_id = 22;
update minenergo_schema.region_directory set pro_name = 'Новгородская область (г Великий Новгород) (49000000000)' where subject_id = 49;
update minenergo_schema.region_directory set pro_name = 'Новосибирская область (г Новосибирск) (50000000000)' where subject_id = 50;
update minenergo_schema.region_directory set pro_name = 'Омская область (г Омск) (52000000000)' where subject_id = 52;
update minenergo_schema.region_directory set pro_name = 'Оренбургская область (г Оренбург) (53000000000)' where subject_id = 53;
update minenergo_schema.region_directory set pro_name = 'Орловская область (г Орёл) (54000000000)' where subject_id = 54;
update minenergo_schema.region_directory set pro_name = 'Хабаровский край (г Хабаровск) (08000000000)' where subject_id = 8;
update minenergo_schema.region_directory set pro_name = 'Пензенская область (г Пенза) (56000000000)' where subject_id = 56;
update minenergo_schema.region_directory set pro_name = 'Пермский край (г Пермь) (57000000000)' where subject_id = 57;
update minenergo_schema.region_directory set pro_name = 'Приморский край (г Владивосток) (05000000000)' where subject_id = 5;
update minenergo_schema.region_directory set pro_name = 'Псковская область (г Псков) (58000000000)' where subject_id = 58;
update minenergo_schema.region_directory set pro_name = 'Республика Башкортостан (г Уфа) (80000000000)' where subject_id = 80;
update minenergo_schema.region_directory set pro_name = 'Республика Бурятия (г Улан-Удэ) (81000000000)' where subject_id = 81;
update minenergo_schema.region_directory set pro_name = 'Республика Дагестан (г Махачкала) (82000000000)' where subject_id = 82;
update minenergo_schema.region_directory set pro_name = 'Республика Ингушетия* (г Магас) (26000000000)' where subject_id = 26;
update minenergo_schema.region_directory set pro_name = 'Республика Калмыкия (г Элиста) (85000000000)' where subject_id = 85;
update minenergo_schema.region_directory set pro_name = 'Республика Карелия (г Петрозаводск) (86000000000)' where subject_id = 86;
update minenergo_schema.region_directory set pro_name = 'Республика Коми (г Сыктывкар) (87000000000)' where subject_id = 87;
update minenergo_schema.region_directory set pro_name = 'Республика Крым (г Симферополь) (35000000000)' where subject_id = 35;
update minenergo_schema.region_directory set pro_name = 'Республика Северная Осетия-Алания (г Владикавказ) (90000000000)' where subject_id = 90;
update minenergo_schema.region_directory set pro_name = 'Республика Татарстан (Татарстан) (г Казань) (92000000000)' where subject_id = 92;
update minenergo_schema.region_directory set pro_name = 'Республика Тыва (г Кызыл) (93000000000)' where subject_id = 93;
update minenergo_schema.region_directory set pro_name = 'Республика Хакасия (г Абакан) (95000000000)' where subject_id = 95;
update minenergo_schema.region_directory set pro_name = 'Ростовская область (г Ростов-на-Дону) (60000000000)' where subject_id = 60;
update minenergo_schema.region_directory set pro_name = 'Рязанская область (г Рязань) (61000000000)' where subject_id = 61;
update minenergo_schema.region_directory set pro_name = 'Самарская область (г Самара) (36000000000)' where subject_id = 36;
update minenergo_schema.region_directory set pro_name = 'Саратовская область (г Саратов) (63000000000)' where subject_id = 63;
update minenergo_schema.region_directory set pro_name = 'Свердловская область (г Екатеринбург) (65000000000)' where subject_id = 65;
update minenergo_schema.region_directory set pro_name = 'Смоленская область (г Смоленск) (66000000000)' where subject_id = 66;
update minenergo_schema.region_directory set pro_name = 'Ставропольский край (г Ставрополь) (07000000000)' where subject_id = 7;
update minenergo_schema.region_directory set pro_name = 'Тамбовская область (г Тамбов) (68000000000)' where subject_id = 68;
update minenergo_schema.region_directory set pro_name = 'Тверская область (г Тверь) (28000000000)' where subject_id = 28;
update minenergo_schema.region_directory set pro_name = 'Томская область (г Томск) (69000000000)' where subject_id = 69;
update minenergo_schema.region_directory set pro_name = 'Тульская область (г Тула) (70000000000)' where subject_id = 70;
update minenergo_schema.region_directory set pro_name = 'Тюменская область (г Тюмень) (71000000000)' where subject_id = 71;
update minenergo_schema.region_directory set pro_name = 'Удмуртская Республика (г Ижевск) (94000000000)' where subject_id = 94;
update minenergo_schema.region_directory set pro_name = 'Ульяновская область (г Ульяновск) (73000000000)' where subject_id = 73;
update minenergo_schema.region_directory set pro_name = 'Челябинская область (г Челябинск) (75000000000)' where subject_id = 75;
update minenergo_schema.region_directory set pro_name = 'Чеченская Республика* (г Грозный) (96000000000)' where subject_id = 96;
update minenergo_schema.region_directory set pro_name = 'Чувашская Республика - Чувашия (г Чебоксары) (97000000000)' where subject_id = 97;
update minenergo_schema.region_directory set pro_name = 'Республика Саха (Якутия) (г Якутск) (98000000000)' where subject_id = 98;
update minenergo_schema.region_directory set pro_name = 'Ярославская область (г Ярославль) (78000000000)' where subject_id = 78;